CREATE TABLE Author(
	Author_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	Name VARCHAR(100) NOT NULL,
	Nationality VARCHAR(50) NOT NULL 
);

CREATE TABLE Book (
    Book_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    Title VARCHAR(100) NOT NULL,
    Gender VARCHAR(50) NOT NULL,
    Publication_Year INTEGER,
    Publisher_ID INTEGER NOT NULL,
    FOREIGN KEY (Publisher_ID) REFERENCES Publisher(Publisher_ID)
);


CREATE TABLE Publisher(
	Publisher_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	Name VARCHAR(100) NOT NULL,
	Country VARCHAR(50) NOT NULL
);

CREATE TABLE Book_Author (
    Book_ID INTEGER NOT NULL,
    Author_ID INTEGER NOT NULL,
    FOREIGN KEY (Book_ID) REFERENCES Book(Book_ID),
    FOREIGN KEY (Author_ID) REFERENCES Author(Author_ID),
    PRIMARY KEY (Book_ID, Author_ID)
);